;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="GameplayAbility_MeleeAttack_GautletsBase",NewTagName="GameplayAbility.MeleeAttack.GautletsBase")
+GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Experience",DevComment="")
+GameplayTagList=(Tag="Effects.HitReaction",DevComment="")
+GameplayTagList=(Tag="Event.Abilities.Changed",DevComment="")
+GameplayTagList=(Tag="Event.ChargeCompleted.SwordCharge",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.End",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.Start",DevComment="")
+GameplayTagList=(Tag="Event.LevelUp",DevComment="")
+GameplayTagList=(Tag="Event.ShootProjectile",DevComment="")
+GameplayTagList=(Tag="Event.Weapon.Equip",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.ChargeAttack",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.ChargeRelease",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Death",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.EquipWeapon",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.HitReaction",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MeleeAttack.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MeleeAttack.GautletsBase",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.MeleeAttack.Sword.AutoAttack",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Dash.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Jump",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.ShootProjectile",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.ShootProjectile.Active",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.UiHidden.Weapon",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damage.Burst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ProjectileImpact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ProjectileSpawn",DevComment="")
+GameplayTagList=(Tag="State.Charging",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="Weapon.Melee.Gauntelts",DevComment="")
+GameplayTagList=(Tag="Weapon.MidRange.Sword",DevComment="")
+GameplayTagList=(Tag="Weapon.Ranged.Gun",DevComment="")

